### ISSUE TITLE
Calls non-existent function of qs

### ISSUE THREAD

**Issue by alamaison** [ideal-postcodes/ideal-postcodes-node#4] opened 2015-09-06 09:54 UTC
qs doesn't have an `escape` function.  Instead it has `stringify`.  I don't think this code could ever have worked :(

**Comment by cblanc** [comment] 2015-09-06 10:27
I wasn't able to find any calls to `escape` on `qs`. I have found invocations of `escape` on `querystring`, however escape is defined on that. These instances can be found [here](https://github.com/ideal-postcodes/ideal-postcodes-node/blob/2c3d8fdce63fc9464454e8840ed75f5048e1f57b/lib/resources/addresses.js#L18), [here](https://github.com/ideal-postcodes/ideal-postcodes-node/blob/2c3d8fdce63fc9464454e8840ed75f5048e1f57b/lib/resources/keys.js#L14), and [here](https://github.com/ideal-postcodes/ideal-postcodes-node/blob/2c3d8fdce63fc9464454e8840ed75f5048e1f57b/lib/resources/postcodes.js#L16)

If you're seeing an `has no method 'escape'` error, could you perhaps paste it into the issue so I can track it down?

**Comment by cblanc** [comment] 2015-09-06 23:15
Thanks for taking the time to look at the code and creating an issue. I'm going to close this though. I've spent some time trying to understand what the issue is here but I don't see where your concern applies. [`qs` is only invoked once in this package and it only uses `stringify`](https://github.com/ideal-postcodes/ideal-postcodes-node/search?utf8=%E2%9C%93&q=qs&type=Code).

Furthermore all instances of `escape` are called on the `querystring` module and are touched by the test suite without issue. `querystring.escape` is documented in both in the [node.js](https://nodejs.org/api/querystring.html#querystring_querystring_escape) and [io.js](https://iojs.org/api/querystring.html#querystring_querystring_escape) as a stable API.

**Closed by cblanc** 2015-09-06 23:15 UTC

**Comment by alamaison** [comment] 2015-09-07 09:03
Hi, sorry for the rubbish bug report.  I was confusing `qs` and `querystring`.

We use npm for managing our modules browser-side, so I didn't realise querystring was a node-specific thing.  Strangely, this is the first npm package I've used that depended on something node-specific!  Sorry for the noise.

**Comment by cblanc** [comment] 2015-09-07 09:44
No worries. It's a pretty small module but potential bugs are always worth looking into. If you have questions you can also drop by - I'm on chat.ideal-postcodes.co.uk
